# Generated by Django 5.0.4 on 2025-03-19 17:00

import main_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=13, validators=[main_app.validators.PhoneNumberValidator(message="Phone number must start with '+359' followed by 9 digits")]),
        ),
    ]
