# Generated by Django 5.0.4 on 2025-03-29 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='co_authors',
            field=models.ManyToManyField(related_name='co_author_books', to='main_app.author'),
        ),
    ]
