# Generated by Django 5.0.4 on 2025-02-27 18:05

from django.db import migrations


def set_rarity_to_item(apps, schema_editor):
    Item = apps.get_model('main_app', 'Item')

    items = Item.objects.all()

    for item in items:
        if item.price <= 10:
            item.rarity = 'Rare'
        elif item.price <= 20:
            item.rarity = 'Very Rare'
        elif item.price <= 30:
            item.rarity = 'Extremely Rare'
        else:
            item.rarity = 'Mega Rare'

        item.save()

def set_item_rarity_to_default(apps, schema_editor):
    Item = apps.get_model('main_app', 'Item')
    default_rarity = Item.objects._meta.get_field('rarity').default

    items = Item.objects.all()

    for item in items:
        item.rarity = default_rarity
        item.save()

class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_item'),
    ]

    operations = [
        migrations.RunPython(set_rarity_to_item, set_item_rarity_to_default)
    ]
