# Generated by Django 5.0.4 on 2025-02-27 18:35
from datetime import timedelta
from django.db import migrations
from main_app.choices import OrderStatusChoices


def change_order_status(apps, schema_editor):
    OrderModel = apps.get_model('main_app', 'Order')

    orders = OrderModel.objects.all()

    for order in orders:
        if order.status == OrderStatusChoices.PENDING:
            order.delivery = order.order_date + timedelta(days=3)
            order.save()

        elif order.status == OrderStatusChoices.COMPLETED:
            order.warranty = '24 months'
            order.save()

        elif order.status == OrderStatusChoices.CANCELLED:
            order.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_order'),
    ]

    operations = [
        migrations.RunPython(code=change_order_status)
    ]
