# Generated by Django 5.0.4 on 2025-02-27 19:52

from django.db import migrations

def set_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    for phone in SmartphoneModel.objects.all():
        phone.price = len(phone.brand) * MULTIPLIER
        phone.save()

def set_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')

    for phone in SmartphoneModel.objects.all():
        if phone.price <= EXPENSIVE_THRESHOLD:
            phone.category = 'Cheap'
        else:
            phone.category = 'Expensive'

        phone.save()

def set_price_and_category(apps, schema_editor):
    set_price(apps, schema_editor)
    set_category(apps, schema_editor)


def reset_price(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_price = SmartphoneModel.objects._meta.get_field('price').default

    for phone in SmartphoneModel.objects.all():
        phone.price = default_price
        phone.save()

def reset_category(apps, schema_editor):
    SmartphoneModel = apps.get_model('main_app', 'Smartphone')
    default_category = SmartphoneModel.objects._meta.get_field('category').default

    for phone in SmartphoneModel.objects.all():
        phone.category = default_category
        phone.save()

def reset_price_category(apps, schema_editor):
    reset_price(apps, schema_editor)
    reset_category(apps, schema_editor)



class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_smartphone'),
    ]

    operations = [
        migrations.RunPython(code=set_price_and_category, reverse_code=reset_price_category)
    ]
