# Generated by Django 5.0.4 on 2025-03-17 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_restaurantreview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantreview',
            options={'ordering': ['-rating'], 'verbose_name': 'Restaurant Review', 'verbose_name_plural': 'Restaurant Reviews'},
        ),
    ]
