# Generated by Django 5.0.4 on 2025-03-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='actor',
            old_name='last_updated_on',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='last_updated_on',
            new_name='last_updated',
        ),
    ]
